### ISSUE TITLE
Include glossary feature

### ISSUE THREAD

**Issue by BirgitBader** [ePages-de/epages-docs#136]
Please include a bar of letters at the top of the page with each letter at the top linked to the respective section. As an example, refer to this: http://europa.eu/legislation_summaries/glossary/

**Comment by mingoscd** [comment]
Implemented on https://github.com/ePages-de/epages-docs/pull/152

**Comment by choffmeister** [comment]
@mingoscd One tip: If you write `Closes #152` anywhere in one of your commit messages, then GitHub closes the issue automatically, when the commit is merged into develop.

**Comment by mingoscd** [comment]
@choffmeister Interesting, I didn't know that. I will use that in the next issue :)
