### ISSUE TITLE
List available resources in sidebar

### ISSUE THREAD

**Issue by BirgitBader** [ePages-de/epages-docs#145]
Our available resources come as a list in the sidebar navigation.
Currently it looks like this:
![bildschirmfoto 2015-07-01 um 07 32 59](https://cloud.githubusercontent.com/assets/10460958/8448104/82251556-1fc3-11e5-9493-1321d0fa6ba5.png)
But it should look like this:
![bildschirmfoto 2015-07-01 um 07 34 21](https://cloud.githubusercontent.com/assets/10460958/8448125/aa962ffc-1fc3-11e5-8c5d-54f79c03f733.png)

**Comment by mingoscd** [comment]
Solved in https://github.com/ePages-de/epages-docs/pull/151
