### ISSUE TITLE
CONTRIBUTING.md states I should PR against master

### ISSUE THREAD

**Issue by depoulo** [ePages-de/epages-docs#287]
Is this still the case? I see much more posts in develop.

**Comment by kayabendroth** [comment]
Maybe that needs to be updated. PRs should go to the default branch, which is ``develop`` here.

**Comment by depoulo** [comment]
nope, according to @BirgitBader this is the correct process.

**Comment by kayabendroth** [comment]
@BirgitBader Please post in here too, so that someone else having the same question can see why blog post PRs should be branched off of ``master`` and need to be pull-requested into ``master``.

**Comment by BirgitBader** [comment]
All blog posts should be committed to `master` because this way they can be released asap and do not conflict with the API documentation.
Make sure to PR against `master`.
